/*
 * generated by Xtext 2.27.0
 */
package xtext.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractMigDslScopeProvider extends DelegatingScopeProvider {
}
