/*
 * generated by Xtext 2.27.0
 */
package xtext;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class MigDslStandaloneSetup extends MigDslStandaloneSetupGenerated {

	public static void doSetup() {
		new MigDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
