/*
 * generated by Xtext 2.27.0
 */
package xtext;

import org.eclipse.core.runtime.CoreException;

import com.google.inject.Binder;

import xtext.configfile.ConfigInitializer;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MigDslRuntimeModule extends AbstractMigDslRuntimeModule {
	
    @Override
    public void configure(Binder binder) {
        super.configure(binder);
        
        try {
			ConfigInitializer.initializeConfigFile();
		} catch (CoreException e) {
			System.out.println(e.getMessage());
		}

    }
}
